/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Yun' at '1/08/15 12:28 AM' with Gradle 2.5-rc-2
 *
 * @author Yun, @date 1/08/15 12:28 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
